### ISSUE TITLE
Proposing new landing page

### ISSUE THREAD

**Issue by mayank3810** [navidrome/website#58]
### **New Website**
As I was going through the landing page, I noticed some UI bugs such as:
About page contents overflow in mobile view.
Search feature not working correctly.
And also, the website seems old.  So I was thinking of developing a new landing page for navidrome.org. The new website will contain all the information that is currently available. If you may allow me to start the development, I will be more than happy to help.

**Comment by deluan** [comment]
Hey, thanks for taking a look at this and sorry for the delay. 

Yes, the current page has these two issues, but I don't have plans to replace it for the foreseen future, because IMO it is a perfect fit for the goals of the page:
- It must provide a good documentation site (main reason to have the site)
- It has to be very very low maintenance, meaning it should not take much of my time to update
- It has to be very simple for contributors to submit PRs to it, to documentation
- It has to be free to host (no server-side code)
- It has to look good. You say it looks old. Well, compared to competing alternatives, I'd say it is one of the best looking out there (subjective, I know)

With that in mind, I selected the Docsy.dev theme for Hugo, and it is really perfect for this purpose. It is a well maintained template (made by Google), focused on documentation and I'm able to customize it a lot without understanding the whole template completely. IMHO, writing something from ground up would not meet the same level of "hands-off" I have with the current solution.

Having said that, I'd love to receive PRs to fix any outstanding issues. The About page is broken because my lack of styling knowledge when I added the screenshots. For the search, one needs to spend a bit time understanding [Docsy search options](https://www.docsy.dev/docs/adding-content/navigation/#site-search-options) and implement a different search method.
